package com.jbpm.carloan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CarData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String carName;

	public CarData() {
	}

	public java.lang.String getCarName() {
		return this.carName;
	}

	public void setCarName(java.lang.String carName) {
		this.carName = carName;
	}

	public CarData(java.lang.String carName) {
		this.carName = carName;
	}

}